### PR TITLE
Bug fixes and code tidy

### PR DESCRIPTION
**Pull request by hallba**
Fixes to different issues raised by Naouel Zerrouk

### CODE REVIEW

**Comment by soli** [comment]
Could you please fix the following:
```
cmd [1] | flake8 --select=C,E,F,W,D,A,I,B --ignore=B950,E501,W503 casq test
casq/bmaExport.py:24:1: E302 expected 2 blank lines, found 1
casq/bmaExport.py:42:1: D102 Missing docstring in public method
casq/bmaExport.py:76:1: D400 First line should end with a period
casq/bmaExport.py:93:17: E126 continuation line over-indented for hanging indent
casq/bmaExport.py:94:17: E123 closing bracket does not match indentation of opening bracket's line
casq/bmaExport.py:108:1: W293 blank line contains whitespace
casq/bmaExport.py:109:1: D102 Missing docstring in public method
casq/bmaExport.py:161:30: E226 missing whitespace around arithmetic operator
casq/bmaExport.py:172:30: E226 missing whitespace around arithmetic operator
casq/bmaExport.py:212:25: E117 over-indented
casq/bmaExport.py:234:30: E226 missing whitespace around arithmetic operator
casq/bmaExport.py:235:30: E226 missing whitespace around arithmetic operator
casq/bmaExport.py:236:30: E226 missing whitespace around arithmetic operator
casq/bmaExport.py:239:29: E225 missing whitespace around operator
casq/bmaExport.py:344:1: W293 blank line contains whitespace
```

**Comment by hallba** [comment]
Last commit fixes flake8 issues

**Comment by soli** [comment]
Thanks… now for a few black issues 😅 (see https://github.com/soli/casq/runs/8252260831?check_suite_focus=true)

**Comment by hallba** [comment]
Fixed black issues but still getting issues reported from CI

**Comment by soli** [comment]
I'll look into it, thanks!

**Comment by soli** [comment]
Ok, for some reason I had conflicts, but even if GH doesn't see it as a merge, I merged it anyway ^^'

**Pull request closed without merging**
